services:
  api:
    image: docker.io/helbender/siq-api:0.5
    restart: always
    build: ./api
    # ports:
    #   - '5051:5051'
    volumes:
      - ./api/database:/app/database
    # environment:
    #   - APPLY_CORS=1
  frontend:
    image: docker.io/helbender/siq-frontend:0.5
    restart: always
    build: ./frontend
    ports:
      - "5173:80" #host:Container
    # volumes:
    #   - /app/node_modules
    #   - ./frontend:/app
    depends_on:
      - api